###

GET http://localhost:4000/logsIn

###
POST http://localhost:4000/logsIn/login
Content-Type: application/json

{
    "ID":"316283696",
    "password":"2233333"
}
###
DELETE http://localhost:4000/logsIn/6211878cec10cb92509b39f8

