GET http://localhost:4000/plots 
###
POST http://localhost:4000/plots/plots
Content-Type: application/json

{
    "ownerName":"or",
    "price":"1000",
    "avaibleForSale":true,
    "row": 170,
    "column": 11,
    "userid": "123456789"
    
}

###
