GET http://localhost:4000/signupUsers 
###

GET http://localhost:4000/signupUsers/620787723dfae1e2b57f686f 

POST http://localhost:4000/signupUsers/signup
Content-Type: application/json

{
    "name":"Slav",
    "ID":"316283696",
    "userType":"Seller",
    "password":"2233333"
}

###
