GET http://localhost:4000/userplots
###
POST http://localhost:4000/userPlot/userplots
Content-Type: application/json

{
   "userId": "Roni",
    "plotId": "1000",
    "avaibleForSale": true
}

###
